services:

  # ==========================================================
  # SkyGuard AI Backend
  # ==========================================================

  backend:

    build:
      context: .
      dockerfile: backend/DockerFile

    container_name: skyguard-backend

    expose:
      - "8000"

    volumes:
      - ./data:/app/data

    restart: unless-stopped


  # ==========================================================
  # SkyGuard AI Frontend
  # ==========================================================

  frontend:

    build:
      context: ./frontend
      dockerfile: DockerFile

    container_name: skyguard-frontend

    ports:
      - "3000:80"

    depends_on:
      - backend

    restart: unless-stopped